// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Dnd__ContainerController from "./dnd/container_controller"
application.register("dnd--container", Dnd__ContainerController)

import Dnd__ItemController from "./dnd/item_controller"
application.register("dnd--item", Dnd__ItemController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)
